# Generated by Django 4.2.7 on 2023-12-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('slug', models.CharField(blank=True, max_length=80, null=True, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog_img/', verbose_name='post preview')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('view_count', models.IntegerField(default='0', verbose_name='view count')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
            },
        ),
    ]
