# Generated by Django 4.2.7 on 2023-12-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Can publish posts'), ('change_description', 'Can change description'), ('change_category', 'Can change category')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
